#!/usr/bin/env python
import rospy
import actionlib
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal

def send_goal():
    rospy.init_node('goal_sender', anonymous=True)
    client = actionlib.SimpleActionClient('move_base', MoveBaseAction)
    client.wait_for_server()

    goal = MoveBaseGoal()
    goal.target_pose.header.frame_id = "map"
    goal.target_pose.header.stamp = rospy.Time.now()
    goal.target_pose.pose.position.x = 1.0  # 目标点 x 坐标
    goal.target_pose.pose.position.y = 2.0  # 目标点 y 坐标
    goal.target_pose.pose.orientation.w = 1.0  # 目标点朝向（四元数表示）

    client.send_goal(goal)
    client.wait_for_result()

if __name__ == '__main__':
    try:
        send_goal()
    except rospy.ROSInterruptException:
        pass